[package]
name = "message_box_bindings"
version = "0.8.0"
authors = ["Microsoft"]
edition = "2018"

[dependencies]
windows = { path = "../../.." }

[build-dependencies]
windows = { path = "../../.." }
