[package]
name = "ocr"
version = "0.8.0"
authors = ["Microsoft"]
edition = "2018"

[dependencies]
bindings = { package = "ocr_bindings", path = "bindings" }
windows = { path = "../.." }
futures = "0.3.5"
